version: "3.5"
services:
  locust-master:
    container_name: locust-master
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: subquery-locust-load
    working_dir: /locust
    networks:
      - locust
    volumes:
      - ./src:/locust
    environment:
      - "WAIT_TIME=${WAIT_TIME}"
      - "BASE_URL=${BASE_URL}"
      - "HTTP_PROXY=${HTTP_PROXY}"
      - "VERIFICATION=${VERIFICATION}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ports:
      - "8089:8089"  # Expose the default Locust web interface port
    command: -f locust_run.py --master --expect-workers=2 --users ${USERS} --spawn-rate ${RAMP_UP} --autostart --run-time ${DURATION} --tags ${TAGS} --html=/locust/report.html
    

  locust-worker-1:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: subquery-locust-load
    working_dir: /locust
    networks:
      - locust
    volumes:
      - ./src:/locust
    environment:
      - "WAIT_TIME=${WAIT_TIME}"
      - "BASE_URL=${BASE_URL}"
      - "HTTP_PROXY=${HTTP_PROXY}"
      - "VERIFICATION=${VERIFICATION}"
    depends_on:
      - locust-master
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    command: -f locust_run.py --worker --master-host=locust-master --users ${USERS} --spawn-rate ${RAMP_UP} --tags ${TAGS}

  locust-worker-2:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: subquery-locust-load
    working_dir: /locust
    networks:
      - locust
    volumes:
      - ./src:/locust
    environment:
      - "WAIT_TIME=${WAIT_TIME}"
      - "BASE_URL=${BASE_URL}"
      - "HTTP_PROXY=${HTTP_PROXY}"
      - "VERIFICATION=${VERIFICATION}"
    depends_on:
      - locust-master
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    command: -f locust_run.py --worker --master-host=locust-master --users ${USERS} --spawn-rate ${RAMP_UP} --tags ${TAGS}


networks:
  locust:
    name: locust
